[package]
name = "cache"
version.workspace = true
edition.workspace = true

[lib]
name = "kp_cache"
path = "src/lib.rs"

[[bin]]
name = "kp_cache"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
base64 = "0.23"
chrono = { workspace = true }
files = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
router = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
