[package]
name = "kodiproxy"
authors = ["bigbro"]
version.workspace = true
edition.workspace = true

[lib]
name = "kp"
path = "src/lib.rs"

[[bin]]
name = "kodiproxy"
path = "src/main.rs"

[build-dependencies]
pkg-config = { workspace = true }

[dependencies]
async-std = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dbus = { workspace = true }
env_logger = { workspace = true }
files = { workspace = true }
form_urlencoded = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
lazy_static = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
quick-xml = { workspace = true, features = ["serialize"] }
regex = { workspace = true }
router = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
mockall = { workspace = true }
rstest = { workspace = true }
test-log = { workspace = true }
url = { workspace = true }
wiremock = { workspace = true }
