[package]
name = "files"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
http = { workspace = true }
hyper = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
router = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
test-log = { workspace = true }
rstest = { workspace = true }
